services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_USER=emi
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=clients-system
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
